//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOTHER3Funland.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MOTHER3Funland.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap bg {
            get {
                object obj = ResourceManager.GetObject("bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bg2 {
            get {
                object obj = ResourceManager.GetObject("bg2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap blue_document_copy {
            get {
                object obj = ResourceManager.GetObject("blue_document_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap butterfly {
            get {
                object obj = ResourceManager.GetObject("butterfly", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap claushead {
            get {
                object obj = ResourceManager.GetObject("claushead", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap disk {
            get {
                object obj = ResourceManager.GetObject("disk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?
        ///Flint
        ///Lucas
        ///Duster
        ///Kumatora
        ///Boney
        ///Salsa
        ///?.
        /// </summary>
        internal static string equippernames {
            get {
                return ResourceManager.GetString("equippernames", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap folder_open_document {
            get {
                object obj = ResourceManager.GetObject("folder_open_document", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap guy {
            get {
                object obj = ResourceManager.GetObject("guy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ioniahead {
            get {
                object obj = ResourceManager.GetObject("ioniahead", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon
        ///Body armor
        ///Headgear
        ///Armgear
        ///Food
        ///Status healer
        ///Battle item
        ///Battle/key item?
        ///Accessory
        ///Memory snake?.
        /// </summary>
        internal static string itemtypes {
            get {
                return ResourceManager.GetString("itemtypes", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap lucashead {
            get {
                object obj = ResourceManager.GetObject("lucashead", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap map {
            get {
                object obj = ResourceManager.GetObject("map", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (none)
        ///Bash thing
        ///Smaaash
        ///Empty?
        ///Empty?
        ///PK Love α
        ///PK Love β
        ///PK Love γ
        ///PK Love Ω
        ///PK Fire α
        ///PK Fire β
        ///PK Fire γ
        ///PK Fire Ω
        ///PK Freeze α
        ///PK Freeze β
        ///PK Freeze γ
        ///PK Freeze Ω
        ///PK Thunder
        ///PK Thunder (no lightning)
        ///PK Thunder 2
        ///PK Thunder 2 (no lightning)
        ///PK Flash
        ///PK Starstorm
        ///PK Ground
        ///Empty?
        ///Lifeup (enemy)
        ///Lifeup α
        ///Lifeup β
        ///Lifeup γ/Ω
        ///Healing (enemy)
        ///Healing α
        ///Healing β
        ///Healing γ/Ω
        ///Refresh
        ///Refresh?
        ///Empty?
        ///Brainshock α
        ///Brainshock Ω
        ///Paralysis α
        ///Paralysis Ω
        ///Hypnosis α
        ///Hypnosis  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string psianimations {
            get {
                return ResourceManager.GetString("psianimations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?
        ///One party member
        ///?
        ///All party members
        ///? (Healing omega)
        ///?
        ///?
        ///?
        ///?
        ///?
        ///?
        ///?
        ///?
        ///One enemy
        ///All enemies
        ///One random strike
        ///Two random strikes
        ///Three random strikes
        ///Four random strikes
        ///Multiple strikes on one enemy.
        /// </summary>
        internal static string psitargets {
            get {
                return ResourceManager.GetString("psitargets", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap salsa {
            get {
                object obj = ResourceManager.GetObject("salsa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?
        ///?
        ///Thomas&apos; store
        ///Chimera lab guy
        ///Vending machine (Clayman factory)
        ///Titiboo refreshment stand
        ///Mouse shop
        ///?
        ///Vending machine (thunder warehouse)
        ///Mole shop
        ///Souvenir shop
        ///Pigmask shop
        ///Vending machine (chimera lab)
        ///Vending machine (thunder tower)
        ///Vending machine (Marshmallow room)
        ///?
        ///Mole cricket (snow)
        ///Saturn shop 1
        ///Saturn shop 2
        ///Mole cricket (volcano)
        ///?
        ///Titiboo merchandise
        ///?
        ///?
        ///Mole cricket (island)
        ///Mole cricket (plateau)
        ///?
        ///?
        ///Mole cricket (Chupichupyoi)
        ///Vending machine (Porky tower)        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string shopnames {
            get {
                return ResourceManager.GetString("shopnames", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap slug {
            get {
                object obj = ResourceManager.GetObject("slug", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sparrow {
            get {
                object obj = ResourceManager.GetObject("sparrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (EMPTY) (1)
        ///Flint (1)
        ///Flint (2)
        ///Lucas (1)
        ///Lucas (2)
        ///Claus (1)
        ///Claus (2)
        ///Claus (3)
        ///Hinawa
        ///Boney (1)
        ///Boney (2)
        ///Kumatora (1)
        ///Kumatora (2)
        ///Kumatora (3)
        ///Wess (1)
        ///Duster (1)
        ///Duster (2)
        ///Fassad (1)
        ///Salsa (1)
        ///Samba
        ///Pusher
        ///Elmore
        ///Ollie (1)
        ///Ollie (2)
        ///Sebastian
        ///Mapson
        ///Jackie (1)
        ///Jackie (2)
        ///Betsy
        ///Tessie
        ///Bateau
        ///Thomas (1)
        ///Thomas (2)
        ///Thomas (3)
        ///Lisa
        ///Mike (1)
        ///Mike (2)
        ///Salsa (2)
        ///Reggie
        ///Bronson (1)
        ///Bronson (2)
        ///Caroline
        ///Angie (1)
        ///Angie (2)
        ///Abbot (1)
        ///Abbot (2)
        ///Abbey
        ///Matt (1)
        ///Matt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string spritenames {
            get {
                return ResourceManager.GetString("spritenames", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap swirl {
            get {
                object obj = ResourceManager.GetObject("swirl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap thunderbomb {
            get {
                object obj = ResourceManager.GetObject("thunderbomb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tazmily 1
        ///Osohe Castle 1
        ///Underground
        ///Railway
        ///Titiboo/Thunder Tower
        ///Titiboo attic
        ///Saturn Valley
        ///Underwater
        ///Cave
        ///New Pork City
        ///Thunder Tower
        ///Chimera lab
        ///Mole Cricket cave
        ///Factory underpass
        ///Factory underground
        ///Osohe Castle 2
        ///Tazmily 2.
        /// </summary>
        internal static string townmapnames {
            get {
                return ResourceManager.GetString("townmapnames", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap vending {
            get {
                object obj = ResourceManager.GetObject("vending", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poison
        ///Paralysis
        ///Sleep
        ///Strange
        ///Cry
        ///Forgetful
        ///Nausea
        ///Fleas
        ///Burned
        ///Solidified
        ///Numbness?
        ///DCMC
        ///Wall staple
        ///Apologize
        ///Make laugh
        ///PK Love
        ///PK Fire
        ///PK Freeze
        ///PK Thunder
        ///Bomb.
        /// </summary>
        internal static string weaknesses {
            get {
                return ResourceManager.GetString("weaknesses", resourceCulture);
            }
        }
    }
}
